-- SEED DATA FOR HOBERG EDU
INSERT INTO public.universities (id, slug, name, country, city, website, admissions_url, international_admissions_url, description, logo_url, image_url, status)
VALUES
('a1000000-0000-0000-0000-000000000001', 'university-of-toronto', 'University of Toronto', 'Canada', 'Toronto, Ontario', 'https://www.utoronto.ca', 'https://future.utoronto.ca/apply', 'https://future.utoronto.ca/international-students', 'Canada''s leading research university, consistently ranked among the top global institutions for technology, medicine, and engineering.', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Utoronto_coat_of_arms.svg/1200px-Utoronto_coat_of_arms.svg.png', 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200&auto=format&fit=crop&q=80', 'published'),
('a1000000-0000-0000-0000-000000000002', 'university-of-oxford', 'University of Oxford', 'United Kingdom', 'Oxford, England', 'https://www.ox.ac.uk', 'https://www.ox.ac.uk/admissions', 'https://www.ox.ac.uk/admissions/graduate/international-applicants', 'The oldest university in the English-speaking world, world-renowned for academic rigor and leadership development.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Oxford-University-Circlet.svg/1200px-Oxford-University-Circlet.svg.png', 'https://images.unsplash.com/photo-1580977276076-ae4b8c219b8e?w=1200&auto=format&fit=crop&q=80', 'published'),
('a1000000-0000-0000-0000-000000000003', 'technical-university-of-munich', 'Technical University of Munich (TUM)', 'Germany', 'Munich, Bavaria', 'https://www.tum.de/en', 'https://www.tum.de/en/studies/application', 'https://www.tum.de/en/studies/international-students', 'Germany''s premier university of technology with world-class engineering, computing research, and low tuition fees.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Logo_of_the_Technical_University_of_Munich.svg/1200px-Logo_of_the_Technical_University_of_Munich.svg.png', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&auto=format&fit=crop&q=80', 'published'),
('a1000000-0000-0000-0000-000000000004', 'university-of-melbourne', 'University of Melbourne', 'Australia', 'Melbourne, Victoria', 'https://www.unimelb.edu.au', 'https://study.unimelb.edu.au/how-to-apply', 'https://study.unimelb.edu.au/international-students', 'Australia''s #1 university, offering distinctive degrees with high graduate employability and research excellence.', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/University_of_Melbourne_Coat_of_Arms.svg/1200px-University_of_Melbourne_Coat_of_Arms.svg.png', 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80', 'published')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.scholarships (id, slug, provider, name, description, degree_levels, eligible_countries, fields, funding_type, funding_amount, tuition_coverage, living_allowance, travel_support, deadline, requirements, application_url, source_url, source_name, is_featured, verification_status)
VALUES
('c1000000-0000-0000-0000-000000000001', 'chevening-scholarship-uk', 'UK Foreign, Commonwealth & Development Office (FCDO)', 'Chevening UK Government Scholarship', 'The UK government’s premier global scholarship programme offering full financial support for a one-year Master’s degree at any UK university.', ARRAY['Master''s'], ARRAY['Nigeria', 'International'], ARRAY['All Fields', 'Technology', 'Public Policy'], 'fully_funded', 'Full tuition + £1,350/mo living stipend + Flights', TRUE, TRUE, TRUE, '2026-11-05 12:00:00+00', '["Undergraduate degree (2:1 or higher)", "Minimum 2 years work experience", "Demonstrated leadership potential"]'::JSONB, 'https://www.chevening.org/apply/', 'https://www.chevening.org', 'UK FCDO Official Portal', TRUE, 'verified'),
('c1000000-0000-0000-0000-000000000002', 'mastercard-foundation-scholars', 'Mastercard Foundation', 'Mastercard Foundation Scholars Program', 'Comprehensive scholarship providing transformative education for young African leaders committed to giving back.', ARRAY['Bachelor''s', 'Master''s'], ARRAY['Nigeria', 'African Countries'], ARRAY['STEM', 'Health', 'Agriculture', 'Business'], 'fully_funded', '100% Tuition + Housing + Living Allowance + Flights', TRUE, TRUE, TRUE, '2026-12-15 23:59:59+00', '["Citizen of an African country", "Academic excellence", "Demonstrated community leadership"]'::JSONB, 'https://mastercardfdn.org/all/scholars/', 'https://mastercardfdn.org', 'Mastercard Foundation Portal', TRUE, 'verified'),
('c1000000-0000-0000-0000-000000000003', 'daad-helmut-schmidt-germany', 'DAAD', 'DAAD Helmut-Schmidt-Programme (Good Governance)', 'Fully funded Master''s scholarships in Germany for future leaders from developing countries.', ARRAY['Master''s'], ARRAY['Nigeria', 'Developing Countries'], ARRAY['Public Policy', 'Economics', 'Governance'], 'fully_funded', 'Full tuition waiver + €934 monthly stipend + Health insurance', TRUE, TRUE, TRUE, '2026-07-31 23:59:59+00', '["First higher education degree with above-average grades", "Motivation letter on governance in home country"]'::JSONB, 'https://www.daad.de/en/', 'https://www.daad.de', 'German Academic Exchange Service', TRUE, 'verified')
ON CONFLICT (slug) DO NOTHING;
